#!/usr/bin/python3
import re
lst = []
with open('input.txt', 'r') as inf:
    lst = re.split('(\d*)',inf.readline().strip())

print(lst)
#print(stringIn)
stringOut = ''
print(len(lst))
for i in range(0, len(lst) - 1, 2):
    stringOut += (lst[i] * int(lst[i + 1]))

print(stringOut)

