#!/usr/bin/python3

classDictionary = {}

def writeClassesInDictionary(d):
    n = int(input())
    while len(classDictionary) != n:
        classAndChildren = str(input()).split()

        clas = classAndChildren[0]
        classDictionary.setdefault(clas, [])
   # if len(classDictionary) == n:
   #     break
###here
        #[:]children = classAndChildren[2:]
        for child in classAndChildren[2:]:
            classDictionary.setdefault(child, [])
            classDictionary.setdefault(clas, []).append(child)
       # if len(classDictionary) == n: 
       #     break
###here
   ## print(classDictionary)
   #### print(len(classDictionary))

writeClassesInDictionary(classDictionary)
print(classDictionary)
for q in range(0, int(input()), 1):
    lst = str(input()).split()
    key = lst[1]
    value = lst[0]
    if value in classDictionary[key]:
        print("Yes")
    else:
        print("No")
